# Generated by Django 4.2.1 on 2023-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
