# Generated by Django 4.2.1 on 2023-05-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_recipestep_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='instruction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
